export enum SolicitacaoENUM {
  ABERTA = "ABERTA",
  ORCADA = "ORCADA",
  REJEITADA = "REJEITADA",
  APROVADA = "APROVADA",
  REDIRECIONADA = "REDIRECIONADA",
  ARRUMADA = "ARRUMADA",
  PAGA = "PAGA",
  FINALIZADA = "FINALIZADA"
}